// <auto-generated />
using System;
using JobApplicationTracker.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobApplicationTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobApplicationTracker.Models.JAEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<bool>("IsWholeDay")
                        .HasColumnType("bit");

                    b.Property<Guid>("JAStatusEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.HasKey("Id");

                    b.HasIndex("JAStatusEntryId")
                        .IsUnique();

                    b.ToTable("JAEventEntries");
                });

            modelBuilder.Entity("JobApplicationTracker.Models.JAStatusEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("JaStatusType")
                        .HasColumnType("int");

                    b.Property<Guid>("JobApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobApplicationId");

                    b.ToTable("JAStatusEntries");
                });

            modelBuilder.Entity("JobApplicationTracker.Models.JobApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("JobApplications");
                });

            modelBuilder.Entity("JobApplicationTracker.Models.JobApplicationMinimal", b =>
                {
                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<bool>("IsWholeDay")
                        .HasColumnType("bit");

                    b.Property<int>("JAStatus")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("jaId")
                        .HasColumnType("uniqueidentifier");

                    b.ToTable((string)null);

                    b.ToView("View_MinimalJA", (string)null);
                });

            modelBuilder.Entity("JobApplicationTracker.Models.JobListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JobApplicationId")
                        .IsUnique();

                    b.ToTable("JobListing");
                });

            modelBuilder.Entity("JobApplicationTracker.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("JobApplicationTracker.Models.UserProfile.Experience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExperienceType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<Guid>("UserResumeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Experience");

                    b.HasDiscriminator<string>("ExperienceType").HasValue("Experience");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("JobApplicationTracker.Models.UserProfile.ResumeSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("UserResumeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserResumeId");

                    b.ToTable("ResumeSkill");
                });

            modelBuilder.Entity("JobApplicationTracker.Models.UserProfile.SkillUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("SkillId");

                    b.ToTable("SkillUsage");
                });

            modelBuilder.Entity("JobApplicationTracker.Models.UserProfile.UserResume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AboutMe")
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<string>("UncategorizedInfo")
                        .HasMaxLength(20000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ResumeEntries");
                });

            modelBuilder.Entity("JobApplicationTracker.Models.UserProfile.Education", b =>
                {
                    b.HasBaseType("JobApplicationTracker.Models.UserProfile.Experience");

                    b.Property<string>("Degree")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("bit");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Notes")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasIndex("UserResumeId");

                    b.HasDiscriminator().HasValue("Education");
                });

            modelBuilder.Entity("JobApplicationTracker.Models.UserProfile.OtherExperience", b =>
                {
                    b.HasBaseType("JobApplicationTracker.Models.UserProfile.Experience");

                    b.Property<string>("Notes")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("UserResumeId");

                    b.ToTable("Experience", t =>
                        {
                            t.Property("Notes")
                                .HasColumnName("OtherExperience_Notes");
                        });

                    b.HasDiscriminator().HasValue("OtherExperience");
                });

            modelBuilder.Entity("JobApplicationTracker.Models.UserProfile.Training", b =>
                {
                    b.HasBaseType("JobApplicationTracker.Models.UserProfile.Experience");

                    b.Property<string>("Certification")
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Type")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasIndex("UserResumeId");

                    b.ToTable("Experience", t =>
                        {
                            t.Property("Notes")
                                .HasColumnName("Training_Notes");
                        });

                    b.HasDiscriminator().HasValue("Training");
                });

            modelBuilder.Entity("JobApplicationTracker.Models.UserProfile.WorkExperience", b =>
                {
                    b.HasBaseType("JobApplicationTracker.Models.UserProfile.Experience");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("JobDescription")
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasIndex("UserResumeId");

                    b.ToTable("Experience", t =>
                        {
                            t.Property("EndDate")
                                .HasColumnName("WorkExperience_EndDate");

                            t.Property("Notes")
                                .HasColumnName("WorkExperience_Notes");

                            t.Property("StartDate")
                                .HasColumnName("WorkExperience_StartDate");
                        });

                    b.HasDiscriminator().HasValue("WorkExperience");
                });

            modelBuilder.Entity("JobApplicationTracker.Models.JAEvent", b =>
                {
                    b.HasOne("JobApplicationTracker.Models.JAStatusEntry", "JAStatusEntry")
                        .WithOne("JAEvent")
                        .HasForeignKey("JobApplicationTracker.Models.JAEvent", "JAStatusEntryId");

                    b.Navigation("JAStatusEntry");
                });

            modelBuilder.Entity("JobApplicationTracker.Models.JAStatusEntry", b =>
                {
                    b.HasOne("JobApplicationTracker.Models.JobApplication", null)
                        .WithMany("StatusHistory")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobApplicationTracker.Models.JobApplication", b =>
                {
                    b.HasOne("JobApplicationTracker.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobApplicationTracker.Models.JobListing", b =>
                {
                    b.HasOne("JobApplicationTracker.Models.JobApplication", null)
                        .WithOne("JobListing")
                        .HasForeignKey("JobApplicationTracker.Models.JobListing", "JobApplicationId");
                });

            modelBuilder.Entity("JobApplicationTracker.Models.UserProfile.ResumeSkill", b =>
                {
                    b.HasOne("JobApplicationTracker.Models.UserProfile.UserResume", null)
                        .WithMany("Skills")
                        .HasForeignKey("UserResumeId");
                });

            modelBuilder.Entity("JobApplicationTracker.Models.UserProfile.SkillUsage", b =>
                {
                    b.HasOne("JobApplicationTracker.Models.UserProfile.Experience", null)
                        .WithMany("Skills")
                        .HasForeignKey("ExperienceId");

                    b.HasOne("JobApplicationTracker.Models.UserProfile.ResumeSkill", null)
                        .WithMany("Usages")
                        .HasForeignKey("SkillId");
                });

            modelBuilder.Entity("JobApplicationTracker.Models.UserProfile.UserResume", b =>
                {
                    b.HasOne("JobApplicationTracker.Models.User", null)
                        .WithOne("UserResume")
                        .HasForeignKey("JobApplicationTracker.Models.UserProfile.UserResume", "UserId");
                });

            modelBuilder.Entity("JobApplicationTracker.Models.UserProfile.Education", b =>
                {
                    b.HasOne("JobApplicationTracker.Models.UserProfile.UserResume", null)
                        .WithMany("Education")
                        .HasForeignKey("UserResumeId");
                });

            modelBuilder.Entity("JobApplicationTracker.Models.UserProfile.OtherExperience", b =>
                {
                    b.HasOne("JobApplicationTracker.Models.UserProfile.UserResume", null)
                        .WithMany("UncategorizedExperiences")
                        .HasForeignKey("UserResumeId");
                });

            modelBuilder.Entity("JobApplicationTracker.Models.UserProfile.Training", b =>
                {
                    b.HasOne("JobApplicationTracker.Models.UserProfile.UserResume", null)
                        .WithMany("Trainings")
                        .HasForeignKey("UserResumeId");
                });

            modelBuilder.Entity("JobApplicationTracker.Models.UserProfile.WorkExperience", b =>
                {
                    b.HasOne("JobApplicationTracker.Models.UserProfile.UserResume", null)
                        .WithMany("WorkExperiences")
                        .HasForeignKey("UserResumeId");
                });

            modelBuilder.Entity("JobApplicationTracker.Models.JAStatusEntry", b =>
                {
                    b.Navigation("JAEvent");
                });

            modelBuilder.Entity("JobApplicationTracker.Models.JobApplication", b =>
                {
                    b.Navigation("JobListing");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("JobApplicationTracker.Models.User", b =>
                {
                    b.Navigation("UserResume");
                });

            modelBuilder.Entity("JobApplicationTracker.Models.UserProfile.Experience", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("JobApplicationTracker.Models.UserProfile.ResumeSkill", b =>
                {
                    b.Navigation("Usages");
                });

            modelBuilder.Entity("JobApplicationTracker.Models.UserProfile.UserResume", b =>
                {
                    b.Navigation("Education");

                    b.Navigation("Skills");

                    b.Navigation("Trainings");

                    b.Navigation("UncategorizedExperiences");

                    b.Navigation("WorkExperiences");
                });
#pragma warning restore 612, 618
        }
    }
}
